#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ceilometermiddleware
Version  : 0.5.0
Release  : 16
URL      : http://tarballs.openstack.org/ceilometermiddleware/ceilometermiddleware-0.5.0.tar.gz
Source0  : http://tarballs.openstack.org/ceilometermiddleware/ceilometermiddleware-0.5.0.tar.gz
Summary  : OpenStack Telemetry middleware for generating metrics
Group    : Development/Tools
License  : Apache-2.0
Requires: ceilometermiddleware-python
Requires: oslo.config
Requires: oslo.messaging
Requires: oslo.utils
Requires: pbr
Requires: pycadf
Requires: six
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
===============================================
Middleware for OpenStack Telemetry (Ceilometer)
===============================================

%package python
Summary: python components for the ceilometermiddleware package.
Group: Default

%description python
python components for the ceilometermiddleware package.


%prep
%setup -q -n ceilometermiddleware-0.5.0

%build
export LANG=C
export SOURCE_DATE_EPOCH=1489272651
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1489272651
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
